// let 3nome = 'Elisson';
let nome3 = 'Elisson';
let $nome = 'Maycon';
let _nome = 'Moreira';
// let @nome = 'teste';
// let !nome = 'teste';
let Nome = 'teste';
let seuNome = 'teste';
let seu_Nome = 'teste';